apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: elu
  namespace: elu
spec:
  maxReplicaCount: 12
  scaleTargetRef:
    name: elu
    apiVersion: apps/v1
    kind: Deployment
    deploymentName: elu
  pollingInterval: 5
  cooldownPeriod: 10
  minReplicaCount: 1
  triggers:
    - type: prometheus
      metadata:
        metricName: event_loop_utilization
        threshold: '20'
        serverAddress: "http://prometheus-k8s.monitoring:9090"
        query: 100*avg(event_loop_utilization{service="elu"})
