apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: elu
  name: elu
  namespace: elu
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    name: web
    nodePort: 30080
  selector:
    app: elu
  type: NodePort
status:
  loadBalancer: {}
